import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { join, basename } from 'path';

const RULES_DIR = join(process.cwd(), 'rules');
const OUTPUT_FILE = join(process.cwd(), 'AGENTS.md');

const IMPACT_ORDER: Record<string, number> = {
  CRITICAL: 0,
  HIGH: 1,
  'MEDIUM-HIGH': 2,
  MEDIUM: 3,
};

interface RuleMeta {
  id: string;
  title: string;
  category: string;
  impact: string;
  tags: string[];
  content: string;
  filename: string;
}

function parseFrontmatter(content: string): { meta: Record<string, string>; body: string } {
  const frontmatterRegex = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/;
  const match = content.match(frontmatterRegex);
  if (!match) return { meta: {}, body: content };

  const meta: Record<string, string> = {};
  const rawMeta = match[1];
  const body = match[2];

  for (const line of rawMeta.split('\n')) {
    const colonIndex = line.indexOf(':');
    if (colonIndex === -1) continue;
    const key = line.slice(0, colonIndex).trim();
    const value = line.slice(colonIndex + 1).trim();
    meta[key] = value.replace(/^["']|["']$/g, '');
  }

  return { meta, body };
}

function loadRules(): RuleMeta[] {
  const files = readdirSync(RULES_DIR)
    .filter(f => f.endsWith('.md') && !f.startsWith('_'))
    .sort();

  const rules: RuleMeta[] = [];

  for (const file of files) {
    const filepath = join(RULES_DIR, file);
    const raw = readFileSync(filepath, 'utf-8');
    const { meta, body } = parseFrontmatter(raw);

    if (!meta.id || !meta.impact) {
      console.warn(`Skipping ${file}: missing id or impact in frontmatter`);
      continue;
    }

    rules.push({
      id: meta.id,
      title: meta.title || meta.id,
      category: meta.category || 'general',
      impact: meta.impact,
      tags: meta.tags ? meta.tags.replace(/[\[\]]/g, '').split(',').map(t => t.trim()) : [],
      content: body.trim(),
      filename: file,
    });
  }

  return rules;
}

function sortRules(rules: RuleMeta[]): RuleMeta[] {
  return [...rules].sort((a, b) => {
    const impactDiff = (IMPACT_ORDER[a.impact] ?? 99) - (IMPACT_ORDER[b.impact] ?? 99);
    if (impactDiff !== 0) return impactDiff;
    return a.id.localeCompare(b.id);
  });
}

function buildAgentsMd(rules: RuleMeta[]): string {
  const lines: string[] = [
    '# AGENTS.md — NestJS Best Practices Rules',
    '',
    '> Auto-generated by `pnpm build`. Do not edit directly — edit files in `rules/` and rebuild.',
    '',
    `> Generated: ${new Date().toISOString()}`,
    `> Total rules: ${rules.length}`,
    '',
    '---',
    '',
    '## Table of Contents',
    '',
  ];

  // Group by impact for TOC
  const byImpact: Record<string, RuleMeta[]> = {};
  for (const rule of rules) {
    if (!byImpact[rule.impact]) byImpact[rule.impact] = [];
    byImpact[rule.impact].push(rule);
  }

  for (const impact of Object.keys(IMPACT_ORDER)) {
    const group = byImpact[impact];
    if (!group || group.length === 0) continue;
    lines.push(`### ${impact} (${group.length})`);
    lines.push('');
    for (const rule of group) {
      const anchor = `rule-${rule.id}`;
      lines.push(`- [${rule.id}](#${anchor}) — ${rule.title}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');

  // Emit each rule
  for (const rule of rules) {
    const anchor = `rule-${rule.id}`;
    lines.push(`<a id="${anchor}"></a>`);
    lines.push('');
    lines.push(`## [${rule.impact}] ${rule.title}`);
    lines.push('');
    lines.push(`**Rule ID:** \`${rule.id}\` | **Category:** \`${rule.category}\` | **Impact:** \`${rule.impact}\``);
    lines.push('');
    if (rule.tags.length > 0) {
      lines.push(`**Tags:** ${rule.tags.map(t => `\`${t}\``).join(', ')}`);
      lines.push('');
    }
    lines.push(rule.content);
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  return lines.join('\n');
}

function main() {
  console.log('Loading rules...');
  const rules = loadRules();
  console.log(`Found ${rules.length} rules`);

  const sorted = sortRules(rules);
  console.log('Rules sorted by impact:');
  for (const [impact, count] of Object.entries(
    sorted.reduce((acc, r) => { acc[r.impact] = (acc[r.impact] || 0) + 1; return acc; }, {} as Record<string, number>)
  )) {
    console.log(`  ${impact}: ${count}`);
  }

  const output = buildAgentsMd(sorted);
  writeFileSync(OUTPUT_FILE, output, 'utf-8');

  const sizeKb = (output.length / 1024).toFixed(1);
  console.log(`\nWrote AGENTS.md (${sizeKb}KB, ${rules.length} rules)`);
}

main();
